[master]
  version = 1

[build.dist]

  [build.dist.master]
    runner="bin/ci"

[build.dist-integration]

  [build.dist-integration.master]
    runner="bin/ci.integration"

[build.branches]

  [build.branches.master]
    runner="bin/ci.branches"

[build.branches-integration]

  [build.branches-integration.master]
    runner="bin/ci.integration"
